### ISSUE TITLE
Req: Save to Draft Folder instead of Outbox

### ISSUE THREAD

**Issue by kychong79** [sotirop/mergelook#1]
Hi, the whole code is excellent. However, may i know how to code it so that the emails are created in the draft folder instead of outbox? Thanks in advance!

**Comment by sotirop** [comment]
Thank you for your kind words! However, I am aware that is not quality code, but just a hack to get the job done!
TBH I don't know how to create the emails in the draft folder. I can have it a look when I got time.
BTW, how would this functionality be helpful to you?

**Comment by kychong79** [comment]
Hi sotirop, thanks for your prompt reply. This is a life-saving hack u have done here.  Firstly, be cos of the IT compliance policy, when running this macro, permission are required for every single email generated. Hence, i thought it would be more effective changing the output to point to the outlook draft folder instead of the outlook outbox to bypass this issue. At the same time, we can actually preview the emails attachments before sending out.

**Comment by kychong79** [comment]
Replace OutLookMailItem.send with OutLookMailItem.save  - It will save the mass emails to the draft folder instead of sending out.
